version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: $uid
        GROUP_ID: $gid
    image: php-lzh-webtool
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=probetag"
      XDEBUG_CONFIG: "client_host=10.244.0.1"
      SSH_AUTH_SOCK: "/ssh-agent"
    volumes:
      - ${HOME}/.composer:/.composer
      - ./:/var/www
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ${HOME}/.ssh:/home/www-data/.ssh:ro
      - ${SSH_AUTH_SOCK}:/ssh-agent:ro
    networks:
      - probetag
  runner:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: $uid
        GROUP_ID: $gid
    image: php-lzh-webtool
    command: php artisan queue:listen
    depends_on:
      - db
      - redis
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=probetag"
      XDEBUG_CONFIG: "client_host=10.244.0.1"
    volumes:
      - ${HOME}/.composer:/.composer
      - ./:/var/www
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - probetag
  redis:
    image: redis
    networks:
      - probetag
  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 13306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - probetag
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - probetag

networks:
  probetag:
    driver: bridge
volumes:
  db:
